// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Palimpsest.Infrastructure.Data;
using Pgvector;

#nullable disable

namespace Palimpsest.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PalimpsestDbContext))]
    [Migration("20251224031829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Palimpsest.Domain.Entities.Assertion", b =>
                {
                    b.Property<Guid>("AssertionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("assertion_id");

                    b.Property<float>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Epistemic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("epistemic");

                    b.Property<string>("EvidenceExcerpt")
                        .HasColumnType("text")
                        .HasColumnName("evidence_excerpt");

                    b.Property<Guid>("EvidenceSegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_segment_id");

                    b.Property<Guid?>("ObjectEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_entity_id");

                    b.Property<string>("ObjectJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("object_json");

                    b.Property<string>("ObjectKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_kind");

                    b.Property<string>("ObjectLiteral")
                        .HasColumnType("text")
                        .HasColumnName("object_literal");

                    b.Property<string>("ObjectType")
                        .HasColumnType("text")
                        .HasColumnName("object_type");

                    b.Property<string>("Predicate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("predicate");

                    b.Property<string>("PredicateNorm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("predicate_norm");

                    b.Property<Guid>("SubjectEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_entity_id");

                    b.Property<DateOnly?>("TimeEnd")
                        .HasColumnType("date")
                        .HasColumnName("time_end");

                    b.Property<DateOnly?>("TimeExact")
                        .HasColumnType("date")
                        .HasColumnName("time_exact");

                    b.Property<string>("TimeScopeKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_scope_kind");

                    b.Property<DateOnly?>("TimeStart")
                        .HasColumnType("date")
                        .HasColumnName("time_start");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid")
                        .HasColumnName("universe_id");

                    b.HasKey("AssertionId");

                    b.HasIndex("EvidenceSegmentId");

                    b.HasIndex("ObjectEntityId");

                    b.HasIndex("SubjectEntityId");

                    b.HasIndex("UniverseId", "EvidenceSegmentId");

                    b.HasIndex("UniverseId", "PredicateNorm");

                    b.HasIndex("UniverseId", "SubjectEntityId", "PredicateNorm");

                    b.ToTable("assertions", (string)null);
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<int?>("BookNumber")
                        .HasColumnType("integer")
                        .HasColumnName("book_number");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SeriesName")
                        .HasColumnType("text")
                        .HasColumnName("series_name");

                    b.Property<string>("Subtype")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Book")
                        .HasColumnName("subtype");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid")
                        .HasColumnName("universe_id");

                    b.HasKey("DocumentId");

                    b.HasIndex("UniverseId", "Title");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.DocumentVersion", b =>
                {
                    b.Property<Guid>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("IngestHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingest_hash");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_text");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.HasKey("VersionId");

                    b.HasIndex("DocumentId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("DocumentId", "IngestHash")
                        .IsUnique();

                    b.ToTable("document_versions", (string)null);
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Dossier", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_text");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid")
                        .HasColumnName("universe_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("EntityId");

                    b.HasIndex("UniverseId", "UpdatedAt")
                        .IsDescending(false, true);

                    b.ToTable("dossiers", (string)null);
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Edge", b =>
                {
                    b.Property<Guid>("EdgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("edge_id");

                    b.Property<Guid>("AssertionId")
                        .HasColumnType("uuid")
                        .HasColumnName("assertion_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FromEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_entity_id");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relation");

                    b.Property<Guid>("ToEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_entity_id");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid")
                        .HasColumnName("universe_id");

                    b.HasKey("EdgeId");

                    b.HasIndex("AssertionId");

                    b.HasIndex("FromEntityId");

                    b.HasIndex("ToEntityId");

                    b.HasIndex("UniverseId", "FromEntityId", "Relation");

                    b.ToTable("edges", (string)null);
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Entity", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid")
                        .HasColumnName("universe_id");

                    b.HasKey("EntityId");

                    b.HasIndex("UniverseId", "EntityType", "CanonicalName");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.EntityAlias", b =>
                {
                    b.Property<Guid>("AliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("alias_id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("AliasNorm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alias_norm");

                    b.Property<float>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0.8f)
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.HasKey("AliasId");

                    b.HasIndex("AliasNorm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AliasNorm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("AliasNorm"), new[] { "gin_trgm_ops" });

                    b.HasIndex("EntityId", "AliasNorm");

                    b.ToTable("entity_aliases", (string)null);
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.EntityMention", b =>
                {
                    b.Property<Guid>("MentionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("mention_id");

                    b.Property<float>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("ResolutionStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resolution_status");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id");

                    b.Property<int>("SpanEnd")
                        .HasColumnType("integer")
                        .HasColumnName("span_end");

                    b.Property<int>("SpanStart")
                        .HasColumnType("integer")
                        .HasColumnName("span_start");

                    b.Property<string>("SurfaceForm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surface_form");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid")
                        .HasColumnName("universe_id");

                    b.HasKey("MentionId");

                    b.HasIndex("EntityId");

                    b.HasIndex("SegmentId");

                    b.HasIndex("UniverseId", "EntityId");

                    b.HasIndex("UniverseId", "SegmentId");

                    b.ToTable("entity_mentions", (string)null);
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_type");

                    b.Property<string>("Progress")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("progress");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid")
                        .HasColumnName("universe_id");

                    b.HasKey("JobId");

                    b.HasIndex("UniverseId", "Status", "CreatedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.QuestionableItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid?>("AssertionId")
                        .HasColumnType("uuid")
                        .HasColumnName("assertion_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<string>("RelatedAssertionIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("related_assertion_ids");

                    b.Property<string>("Resolution")
                        .HasColumnType("jsonb")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubjectEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_entity_id");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("uuid")
                        .HasColumnName("universe_id");

                    b.HasKey("ItemId");

                    b.HasIndex("SubjectEntityId");

                    b.HasIndex("UniverseId", "Status", "ItemType");

                    b.ToTable("questionable_items", (string)null);
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Segment", b =>
                {
                    b.Property<Guid>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id");

                    b.Property<string>("ChapterLabel")
                        .HasColumnType("text")
                        .HasColumnName("chapter_label");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("SectionPath")
                        .HasColumnType("text")
                        .HasColumnName("section_path");

                    b.Property<string>("SourceLocator")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_locator");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.HasKey("SegmentId");

                    b.HasIndex("VersionId", "Ordinal");

                    b.ToTable("segments", (string)null);
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.SegmentEmbedding", b =>
                {
                    b.Property<Guid>("SegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)")
                        .HasColumnName("embedding");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.HasKey("SegmentId");

                    b.ToTable("segment_embeddings", (string)null);
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Universe", b =>
                {
                    b.Property<Guid>("UniverseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("universe_id");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text")
                        .HasColumnName("author_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("UniverseId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("universes", (string)null);
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Assertion", b =>
                {
                    b.HasOne("Palimpsest.Domain.Entities.Segment", "EvidenceSegment")
                        .WithMany("Assertions")
                        .HasForeignKey("EvidenceSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palimpsest.Domain.Entities.Entity", "ObjectEntity")
                        .WithMany("ObjectAssertions")
                        .HasForeignKey("ObjectEntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Palimpsest.Domain.Entities.Entity", "SubjectEntity")
                        .WithMany("SubjectAssertions")
                        .HasForeignKey("SubjectEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palimpsest.Domain.Entities.Universe", "Universe")
                        .WithMany("Assertions")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvidenceSegment");

                    b.Navigation("ObjectEntity");

                    b.Navigation("SubjectEntity");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Document", b =>
                {
                    b.HasOne("Palimpsest.Domain.Entities.Universe", "Universe")
                        .WithMany("Documents")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.DocumentVersion", b =>
                {
                    b.HasOne("Palimpsest.Domain.Entities.Document", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Dossier", b =>
                {
                    b.HasOne("Palimpsest.Domain.Entities.Entity", "Entity")
                        .WithOne("Dossier")
                        .HasForeignKey("Palimpsest.Domain.Entities.Dossier", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palimpsest.Domain.Entities.Universe", "Universe")
                        .WithMany("Dossiers")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Edge", b =>
                {
                    b.HasOne("Palimpsest.Domain.Entities.Assertion", "Assertion")
                        .WithMany("Edges")
                        .HasForeignKey("AssertionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palimpsest.Domain.Entities.Entity", "FromEntity")
                        .WithMany("EdgesFrom")
                        .HasForeignKey("FromEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palimpsest.Domain.Entities.Entity", "ToEntity")
                        .WithMany("EdgesTo")
                        .HasForeignKey("ToEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palimpsest.Domain.Entities.Universe", "Universe")
                        .WithMany("Edges")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assertion");

                    b.Navigation("FromEntity");

                    b.Navigation("ToEntity");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Entity", b =>
                {
                    b.HasOne("Palimpsest.Domain.Entities.Universe", "Universe")
                        .WithMany("Entities")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.EntityAlias", b =>
                {
                    b.HasOne("Palimpsest.Domain.Entities.Entity", "Entity")
                        .WithMany("Aliases")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.EntityMention", b =>
                {
                    b.HasOne("Palimpsest.Domain.Entities.Entity", "Entity")
                        .WithMany("Mentions")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Palimpsest.Domain.Entities.Segment", "Segment")
                        .WithMany("Mentions")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palimpsest.Domain.Entities.Universe", "Universe")
                        .WithMany("EntityMentions")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Segment");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Job", b =>
                {
                    b.HasOne("Palimpsest.Domain.Entities.Universe", "Universe")
                        .WithMany("Jobs")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.QuestionableItem", b =>
                {
                    b.HasOne("Palimpsest.Domain.Entities.Entity", "SubjectEntity")
                        .WithMany()
                        .HasForeignKey("SubjectEntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Palimpsest.Domain.Entities.Universe", "Universe")
                        .WithMany("QuestionableItems")
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubjectEntity");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Segment", b =>
                {
                    b.HasOne("Palimpsest.Domain.Entities.DocumentVersion", "Version")
                        .WithMany("Segments")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.SegmentEmbedding", b =>
                {
                    b.HasOne("Palimpsest.Domain.Entities.Segment", "Segment")
                        .WithOne("Embedding")
                        .HasForeignKey("Palimpsest.Domain.Entities.SegmentEmbedding", "SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Assertion", b =>
                {
                    b.Navigation("Edges");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Document", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.DocumentVersion", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Entity", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Dossier");

                    b.Navigation("EdgesFrom");

                    b.Navigation("EdgesTo");

                    b.Navigation("Mentions");

                    b.Navigation("ObjectAssertions");

                    b.Navigation("SubjectAssertions");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Segment", b =>
                {
                    b.Navigation("Assertions");

                    b.Navigation("Embedding");

                    b.Navigation("Mentions");
                });

            modelBuilder.Entity("Palimpsest.Domain.Entities.Universe", b =>
                {
                    b.Navigation("Assertions");

                    b.Navigation("Documents");

                    b.Navigation("Dossiers");

                    b.Navigation("Edges");

                    b.Navigation("Entities");

                    b.Navigation("EntityMentions");

                    b.Navigation("Jobs");

                    b.Navigation("QuestionableItems");
                });
#pragma warning restore 612, 618
        }
    }
}
